server:
  port: 20200
  undertow:
    threads:
      io: 4
      worker: 32
spring:
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
  datasource:
    url: jdbc:h2:mem:temp
    driver-class-name: org.h2.Driver
    username: SA
    password:

mercury:
  init: false
  name: Mercury
  version: 1.0.0