name: Build

on:
  push:
    branches: 
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'
#       - '.github/workflows/**'

jobs:
  build_page:
    name: Build Page
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: './page/yarn.lock'
        cache: 'yarn'
    - name: Yarn CLI
      uses: CultureHQ/actions-yarn@v1.0.1
    - run: yarn install
      working-directory: './page'
    - run: yarn build
      working-directory: './page'
    
  build_service:
    name: Build Service
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
